### ISSUE TITLE
让我们用Nestjs来重写一个CNode(中)

### ISSUE THREAD

**Issue by jiayisheji** [jiayisheji/blog#19]
我发现比我想象要长，打算把实战部分拆分成中和下来讲解。

通过[上篇](https://github.com/jiayisheji/blog/issues/18)学习，相信大家对 `Nest` 有大概印象，但是你还是看不出它有什么特别的地方，下篇将为你介绍项目实战中`Nest`如何使用各种特性和一些坑和解决方案。[源码](https://github.com/jiayisheji/nest-cnode)

这篇主要内容：
- 项目架构规划
- 入口文件和依赖安装
- 模板引擎配置
- 静态文件配置
- 系统配置和应用配置
- 静态模板`layout.html`和`index.html`编写
- 用户表配置
- 注册业务编写
- 使用node-mailer发送邮件
- 本地登录
- 第三方认证github登录
- session和cookie
- 找回密码和登出

## 项目架构规划设计

一个好的文件结构约定，会让我们开发合作、维护管理，节省很多不必要沟通。

这里我`scr`文件规划：

文件 | 说明
---|---
main.ts | 入口
main.hmr.ts | 热更新入口
app.service.ts | APP服务（选择）
app.module.ts | APP模块（根模块，必须）
app.controller.ts | APP控制器（选择）
app.controller.spec.ts | APP控制器单元测试用例（选择）
config | 配置模块
core | 核心模块（申明过滤器、管道、拦截器、守卫、中间件、全局模块）
feature | 特性模块（主要业务模块）
shared | 共享模块（共享mongodb、redis封装服务、通用服务）
tools | 工具（提供一些小工具函数）

> 这是我参考我`Angular`项目的结构，写了几个`nest`项目后发现这个很不错。把`mongodb`服务和业务模块分开，还有一个好处就是减少`nest`循环依赖注入深坑，后面会讲怎么解决它。

### 入口文件 main.ts

打开`main.ts`文件

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```

`NestFactory` 创建一个app实例，监听`3000`端口。

```ts
/**
 * Creates an instance of the NestApplication
 * @returns {Promise}
 */
create(module: any): Promise<INestApplication & INestExpressApplication>;
create(module: any, options: NestApplicationOptions): Promise<INestApplication & INestExpressApplication>;
create(module: any, httpServer: FastifyAdapter, options?: NestApplicationOptions): Promise<INestApplication & INestFastifyApplication>;
create(module: any, httpServer: HttpServer, options?: NestApplicationOptions): Promise<INestApplication & INestExpressApplication>;
create(module: any, httpServer: any, options?: NestApplicationOptions): Promise<INestApplication & INestExpressApplication>;
```

`create`方法有1-3参数，第一个是入口模块`AppModule`, 第二个是一个`httpServer`,如果要绑定`Express`中间件，需要传递`Express`实例。第三个全局配置：

- logger 打印日志
- cors 跨域配置
- bodyParser post和put解析body中间件配置
- httpsOptions https配置

`app` 带方法有哪些
`INestApplication`下
- init 初始化应用程序，直接调用此方法并非强制。（效果不明）
- use 注册中间件
- enableCors 启用CORS（跨源资源共享）
- listen 启动应用程序。
- listenAsync 同步启动应用程序。
- setGlobalPrefix 注册每个HTTP路由路径的前缀
- useWebSocketAdapter 安装将在网关内部使用的Ws适配器。使用时覆盖，默认`socket.io`库。
- connectMicroservice 将微服务连接到NestApplication实例。 将应用程序转换为混合实例。
- getMicroservices 返回连接到NestApplication的微服务的数组。
- getHttpServer 返回基础的本地HTTP服务器。
- startAllMicroservices 异步启动所有连接的微服务
- startAllMicroservicesAsync 同步启动所有连接的微服务
- useGlobalFilters 将异常过滤器注册为全局过滤器（将在每个HTTP路由处理程序中使用）
- useGlobalPipes 将管道注册为全局管道（将在每个HTTP路由处理程序中使用）
- useGlobalInterceptors 将拦截器注册为全局拦截器（将在每个HTTP路由处理器中使用）
- useGlobalGuards 注册警卫作为全局警卫（将在每个HTTP路由处理程序中使用）
- close 终止应用程序（包括NestApplication，网关和每个连接的微服务）
`INestExpressApplication`下
- set 围绕本地`express.set()`方法的包装函数。
- engine 围绕本地`express.engine()`方法的包装函数。
- enable 围绕本地`express.enable()`方法的包装函数。
- disable 围绕本地`express.disable()`方法的包装函数。
- useStaticAssets 为静态资源设置基础目录。围绕本地`express.static(path, options)`方法的包装函数。
- setBaseViewsDir 设置模板（视图）的基本目录。围绕本地`express.set('views', path)`方法的包装函数。
- setViewEngine 为模板（视图）设置视图引擎。围绕本地`express.set('view engine', engine)`方法的包装函数。

### 依赖安装

因为目前CNode采用`Egg`编写，里面大量使用与`Egg`集成的`egg-xxx`包，这里我把相关的连对应的依赖都一一来出来。

#### 模板引擎

`Egg-CNode`使用`egg-view-ejs`，本项目使用`ejs`包，唯一缺点没有`layout`功能，可以麻烦点，在每个文件引入头和尾即可，也有另外一个包`ejs-mate`，它有`layout`功能，后面会介绍它怎么使用。

#### redis

`Egg-CNode`使用`egg-redis`操作`redis`，其实它是包装的`ioredis`包，我也一直在nodejs里使用这个包，需要安装生产`ioredis`和开发`@types/ioredis`

#### mongoose

`Egg-CNode`使用`egg-mongoose`操作`mongodb`，`Nest`提供了`@nestjs/mongoose`，需要安装生产`mongoose`和开发`@types/mongoose`

#### passport

`Egg-CNode`使用`egg-passport、egg-passport-github、egg-passport-local`做身份验证，`Nest`提供了`@nestjs/passport`，需要安装生产`passport、passport-github、passport-local`

其他依赖在后面用到时候在详细介绍，这几个是比较重要的依赖。

## 配置 Views 视图模板和 public 静态资源

`CNode` 使用的是`egg-ejs`,为了简单点，减少静态文件编写，我也用`ejs`。发现区别就是少了`layout`功能，需要我们拆分`layout/header.ejs`和`layout/footer.ejs`在使用了。
但是有一个包可以做到类似的功能`ejs-mate`，这个是[@JacksonTian](https://github.com/JacksonTian) 朴灵大神的作品。

新建模板存放`views`文件夹(root/views)和静态资源存放`public`文件夹(root/public)

**注意**：`nest-cli`默认只处理`src`里面的ts文件，如有其他文件需要自己写脚本处理，`gulp`或者`webpack`都可以，这里就简单一点，直接把`views`和`public`放在`src`平级的根目录里面了。后面会说怎么处理它们设置问题。

### 模板引擎

安装`ejs-mate`依赖：

```bash
npm install ejs-mate --save
```

用法很简单了，关于文件名后缀，默认使用`.ejs`，`.ejs`虽然会让它语法高亮，有个坑就`html`标签不会自动补全提示。那需要换成`.html`后缀。

设置模板引擎：

```ts
import { join } from 'path';
import * as ejsMate from 'ejs-mate';
async function bootstrap() {
    ....
      // 获取根目录 nest-cnode
    const rootDir = join(__dirname, '..');
    // 指定视图引擎 处理.html后缀文件
    app.engine('html', ejsMate);
    // 视图引擎
    app.set('view engine', 'html');
    // 配置模板（视图）的基本目录
    app.setBaseViewsDir(join(rootDir, 'views'));
    ...
}
```

> **注意**：当前启动程序是`src/main.ts`，因为`views`和`public`在根目录，所有我们就需要去获取获取根目录。其他注释已经说明，就不再赘述。

使用模板引擎：

1. 我们在`views`文件夹里面新建一个`layout.html`和一个`index.html`。

2. 写通用的`layout.html`

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>我是layout模板</title>
</head>
<body>
    <%- body -%>
</body>
```

3. 写的`index.html`

```html
<% layout('layout') -%>
<h1>我是首页</h1>  
```

4. 渲染模板引擎

```ts
import { Get, Controller, Render } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  @Render('index')
  root() {
    return {};
  }
}
```

**注意**：`@Render()`里面一定要写模板文件名(可以省略后缀)，不然访问页面显示是`json`对象。

访问首页`http://localhost:3000/`看结果。

![3nc4l2 l_nbp_di0fkomamc](https://user-images.githubusercontent.com/6111778/44764383-043ced00-ab82-11e8-8ae4-35d9cedcd26d.png)

`ejs-mate`语法：

`ejs-mate`兼容[ejs](https://ejs.bootcss.com/)语法，语法很简单，这里顺便带一下：

- <% '脚本' 标签，用于流程控制，无输出。
- <%_ 删除其前面的空格符
- <%= 输出数据到模板（输出是转义 HTML 标签）
- <%- 输出非转义的数据到模板
- <%# 注释标签，不执行、不输出内容
- <%% 输出字符串 '<%'
- %> 一般结束标签
- -%> 删除紧随其后的换行符
- _%> 将结束标签后面的空格符删除

说几个常用的写法：

```ejs

<% 直接写js代码，不输出：%>

<ul>
  <% users.forEach(function(user){ %>
    <%- include('user/show', {user: user}); %>
  <% }); %>
</ul>

<%# 输出变量：%>

<%= '变量' %>

<%# 输出HTML：%>

<%- '<h1>标题</h1>' %>

<%# 引入其他ejs文件（注意：2个参数，第一个是路径：相对于当前模板路径中的模板片段包含进来；第二个是传递数据对象。）：%>

<%- include('user/show', {user: user}); %>

```

说明：

**注意**：以上语法基本一样，有一样不一样，`include`需要用`partial`代替。他们俩用法一模一样。

`layout`功能，需要在引用的页面，比如`index.html`里面使用`<% layout('layout') -%>`，**注意**：这里`'layout'`是指`layout.html`。

还有一个比较重要的功能是`block`。它是在指定的位置插入自定义内容。类似于`angularjs`的`transclude`，`angular`的`<ng-content select="[xxx]"></ng-content>`，`vue`的`<slot></slot>`。

`slot`写法：

```ejs
<%- block('head').toString() %>
```

`block('head')`，是一个占位标识符，`toString`是合并所有的插入使用`join`转成字符串。

使用：

```ejs
<% block('head').append('<link type="text/css" href="/append.css">') %>
<% block('head').prepend('<link type="text/css" href="/prepend.css">') %>
```

`append`和`prepend`是插入的顺序，`append`总是插槽位置插入在最后，`prepend`总是插槽位置插入在最前。

我们来验证一下。

现在`layout.html`的`head`里面写上

```html
<head>
    ...
    <link type="text/css" href="/style.css">
    <%- block('head').toString() %>
</head>
```

`index.html`的结尾写上

```html
...
<% block('head').append('<link type="text/css" href="/append.css">') %>
<% block('head').prepend('<link type="text/css" href="/prepend.css">') %>
<% block('head').prepend('<link type="text/css" href="/prepend2.css">') %>
<% block('head').append('<link type="text/css" href="/append2.css">') %>  
```

访问首页`http://localhost:3000/`看结果。

![7d kp 0rh t 7 i4](https://user-images.githubusercontent.com/6111778/44764409-1ae34400-ab82-11e8-9177-aba90b3d799d.png)

**注意**：`index.html`里书写`block('head').append`的位置不影响它显示插槽的位置，只受定义插槽`<%- block('head').toString() %>`

还有一个方法`replace`，没看懂怎么用的，文档里面也没有说明，基本`append`、`prepend`、`toString`就够用了。

总结：`toString`是定义插槽位置，`append`、`prepend`往插槽插入指定的内容。他们主要做什么了，`layout`载入公共的`css`、`js`，如果有的页面有不一样地方，就需要插入当前页面的js了，那么一来这个插槽功能就有用，如果使用`layout`功能插入，就会包含在`layout`位置，无论是语义还是加载都是不合理的。就有了`block`的功能，在另一款模板引擎`Jade`里面也有同样的功能也叫`block`功能。

### 静态资源

`public`文件夹里面内容直接拷贝`egg-cnode`下的`public`的静态资源

还需要安装几个依赖：

```bash
npm i --save loader loader-connect loader-builder
```

这几个模块是加载css和js使用，也是[@JacksonTian](https://github.com/JacksonTian) 朴灵大神的作品。

main.ts配置

```ts
import { join } from 'path';

import * as loaderConnect from 'loader-connect';

async function bootstrap() {
  ...
  // 根目录 nest-cnode
  const rootDir = join(__dirname, '..');
  // 注意：这个要在express.static之前调用，loader2.0之后要使用loader-connect
  // 自动转换less为css
  if (isDevelopment) {
    app.use(loaderConnect.less(rootDir));
  }
  // 所有的静态文件路径都前缀"/public", 需要使用“挂载”功能
  app.use('/public', express.static(join(rootDir, 'public')));
  // 官方指定是这个 默认访问根目录
  // app.useStaticAssets(join(__dirname, '..', 'public'));
  ...
}
```

**注意**：如果静态文件路径都前缀`/public`，需要使用`use`去挂载`express.static`路径。只有`express`是这样的

```ts
  useStaticAssets(path: string, options: ServeStaticOptions) {
    return this.use(express.static(path, options));
  }
```

它的源码是这样写的，如果这样的，你的静态资源路径就是从根目录开始，如果需要加前缀`/public`，就需要`express`提供的[方式](http://expressjs.jser.us/4x_zh-cn/api.html#app.use)

测试我们静态资源路径设置是否正常工作

在`index.html`里面引入`public/images/logo.png`图片

```html
...
<img src="/public/images/logo.png" alt="logo">
...
```

![l8p0 psc xxuk6 zyea0nvs](https://user-images.githubusercontent.com/6111778/44764424-2e8eaa80-ab82-11e8-9a94-44979c2265e6.png)

如果有问题，请找原因，路径是否正确，设置是否正确，如果都ok，还是不能访问，可以联系我。

关于`loader`使用：

```html
  <!-- style -->
  <%- Loader('/public/stylesheets/index.min.css')
  .css('/public/libs/bootstrap/css/bootstrap.css')
  .css('/public/stylesheets/common.css')
  .css('/public/stylesheets/style.less')
  .css('/public/stylesheets/responsive.css')
  .css('/public/stylesheets/jquery.atwho.css')
  .css('/public/libs/editor/editor.css')
  .css('/public/libs/webuploader/webuploader.css')
  .css('/public/libs/code-prettify/prettify.css')
  .css('/public/libs/font-awesome/css/font-awesome.css')
  .done(assets, config.site_static_host, config.mini_assets)
  %>

  <!-- scripts -->
  <%- Loader('/public/index.min.js')
  .js('/public/libs/jquery-2.1.0.js')
  .js('/public/libs/lodash.compat.js')
  .js('/public/libs/jquery-ujs.js')
  .js('/public/libs/bootstrap/js/bootstrap.js')
  .js('/public/libs/jquery.caret.js')
  .js('/public/libs/jquery.atwho.js')
  .js('/public/libs/markdownit.js')
  .js('/public/libs/code-prettify/prettify.js')
  .js('/public/libs/qrcode.js')
  .js('/public/javascripts/main.js')
  .js('/public/javascripts/responsive.js')
  .done(assets, config.site_static_host, config.mini_assets)
  %>
```

- `Loader`可以加载`.js`方法也可以加载`.coffee`、`.es`类型的文件，`.css`方法可以加载`.less`、`.styl`文件。
- `Loader('/public/index.min.js')`是合并后名字
- `.js('/public/libs/jquery-2.1.0.js')`是加载每一个文件地址
- `.done(assets, config.site_static_host, config.mini_assets)`是处理文件，第一个参数合并压缩后的路径（后面讲解），第二个参数静态文件服务器地址，第三个参数是否压缩

`assets`从哪里来

在`package.json`的`scripts`配置

```json
{
    ...
    "assets": "loader /views /"
}
```

loader的写法是：`loader <views_dir> <output_dir>`。`views_dir`是模板引擎目录，`output_dir`是`assets.json`文件输出的目录，`/`表示根目录。

```bash
npm run assets
```

直接运行会报错，这个问题在`egg-node`有人提[issues](https://github.com/cnodejs/egg-cnode/issues/129)

![z90d4zb w t t26e_2 l](https://user-images.githubusercontent.com/6111778/44764434-3b130300-ab82-11e8-9322-088c7688949a.png)

主要是静态资源`css`引用的背景图片和字体地址有错误，需要修改哪些文件：

错误信息：

`no such file or directory, open 'E:\github\nest-cnode\E:\public\img\glyphicons-halflings.png'`

谁引用了它 `Error! File:/public/libs/bootstrap/css/bootstrap.css`

/public/libs/bootstrap/css/bootstrap.css

```css
...
[class^="icon-"],
[class*=" icon-"] {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin-top: 1px;
    *margin-right: .3em;
    line-height: 14px;
    vertical-align: text-top;
    background-image: url("/public/libs/bootstrap/img/glyphicons-halflings.png");
    background-position: 14px 14px;
    background-repeat: no-repeat;
}
...

.icon-white,
.nav-pills > .active > a > [class^="icon-"],
.nav-pills > .active > a > [class*=" icon-"],
.nav-list > .active > a > [class^="icon-"],
.nav-list > .active > a > [class*=" icon-"],
.navbar-inverse .nav > .active > a > [class^="icon-"],
.navbar-inverse .nav > .active > a > [class*=" icon-"],
.dropdown-menu > li > a:hover > [class^="icon-"],
.dropdown-menu > li > a:focus > [class^="icon-"],
.dropdown-menu > li > a:hover > [class*=" icon-"],
.dropdown-menu > li > a:focus > [class*=" icon-"],
.dropdown-menu > .active > a > [class^="icon-"],
.dropdown-menu > .active > a > [class*=" icon-"],
.dropdown-submenu:hover > a > [class^="icon-"],
.dropdown-submenu:focus > a > [class^="icon-"],
.dropdown-submenu:hover > a > [class*=" icon-"],
.dropdown-submenu:focus > a > [class*=" icon-"] {
    background-image: url("/public/libs/bootstrap/img/glyphicons-halflings-white.png");
}
...
```

大约`2296`和`2320`行位置，你可以用查找搜索`glyphicons-halflings.png`，默认是`background-image: url("../img/glyphicons-halflings.png");`, 替换为上面写法。

/public/stylesheets/style.less

```css
...
.navbar .search-query {
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  background: #888 url('/public/images/search.png') no-repeat 4px 4px;
  padding: 3px 5px 3px 22px;
  color: #666;
  border: 0px;
  margin-top: 2px;

  &:hover {
    background-color: white;
  }
  transition: all 0.5s;

  &:focus, &.focused {
    background-color: white;
  }
}
...
```

大约`850`行位置

> 简单解释就是换成相对于根目录的路径，后面错误就类似。

![45 7el q a5ph tf g84r 0](https://user-images.githubusercontent.com/6111778/44764444-45350180-ab82-11e8-9f65-a6b319a11fec.png)

打包成功以后会输出一个`assets.json`在根目录。`assets`指的就是这个json文件，后面我们会讲如果把它们关联起来。
